# =============================================
#  PERFIL PADRAO: H2 (sala de aula / sem MySQL)
# =============================================

spring.datasource.url=jdbc:h2:mem:assisconnect
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.address=0.0.0.0
server.port=8080